CONFIG_ZMK_POINTING=y
# optional, nicer scroll feel on macOS
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_EXPERIMENTAL_RGB_LAYER=y
